apiVersion: v1
kind: ConfigMap
metadata:
  name: poker-session-config
  namespace: {{ .Values.namespace }}
  labels:
    app: poker-session
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  DATABASE_URL: {{ .Values.configMap.DATABASE_URL }}
