apiVersion: apps/v1
kind: Deployment
metadata:
  name: poker-session-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: poker-session
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: poker-session
  template:
    metadata:
      labels:
        app: poker-session
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: poker-session
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: poker-session-config
                  key: DATABASE_URL
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: poker-session-secret
                  key: DATABASE_PASSWORD
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
