apiVersion: v1
kind: Service
metadata:
  name: poker-session-service
  namespace: {{ .Values.namespace }}
  labels:
    app: poker-session
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: poker-session
