name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Project1/requirements.txt

    - name: Test with pytest
      run: |
        cd Project1
        pytest

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Deploy with Helm
      run: |
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
        helm install poker-session-logger ./Project2/helm/poker-session-logger --namespace poker-app --create-namespace
