apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server
  namespace: poker-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['prometheus-alertmanager.poker-app.svc.cluster.local:9093']
    rule_files:
      - /etc/config/alerting_rules.yaml
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'fastapi'
        static_configs:
          - targets: ['poker-session-service.poker-app.svc.cluster.local:80']
        metrics_path: /metrics
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - target_label: __address__
            replacement: poker-session-service.poker-app.svc.cluster.local:80
          - source_labels: [__param_target]
            target_label: instance
