namespace: poker-app
replicaCount: 3
image:
  repository: poker-session-logger
  tag: latest
  pullPolicy: Never

service:
  type: LoadBalancer
  port: 80

configMap:
  DATABASE_URL: "sqlite:///./poker_sessions.db"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

secret:
  DATABASE_PASSWORD: "pass"

serverFiles:
  prometheus.yml:
    global:
      scrape_interval: 15s
    rule_files:
      - /etc/config/alerting_rules.yaml
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'fastapi'
        static_configs:
          - targets: ['poker-session-service.poker-app.svc.cluster.local:80']
        metrics_path: /metrics
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - target_label: __address__
            replacement: poker-session-service.poker-app.svc.cluster.local:80
          - source_labels: [__param_target]
            target_label: instance

extraArgs:
  - "--web.enable-lifecycle"

extraConfigmapMounts:
  - name: alert-rules
    configMap: prometheus-alert-rules
    mountPath: /etc/config/alerting_rules.yaml
    subPath: alerting_rules.yaml

extraVolumeMounts:
  - name: alert-rules
    mountPath: /etc/config/alerting_rules.yaml
    subPath: alerting_rules.yaml

extraVolumes:
  - name: alert-rules
    configMap:
      name: prometheus-alert-rules
